name: CI

on:
  push:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-repo

      - name: Format check
        run: bun run fmt:check

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Typecheck
        run: bun run typecheck

  test:
    needs: [check]

    name: Test
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-repo

      - name: Test
        run: bun run test:ci

  examples:
    needs: [check]

    name: Examples
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-repo

      - name: Examples
        run: bun run examples

  benchmark-memory-footprint:
    needs: [check]

    name: Benchmark / Memory Footprint
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-repo

      - name: Memory Footprint
        run: bun run --filter './benchmarks/memory-footprint' start

  benchmark-processing-capacity:
    needs: [check]

    name: Benchmark / Processing Capacity
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-repo

      - name: Processing Capacity
        run: bun run --filter './benchmarks/processing-capacity' start

  benchmark-query-performance:
    needs: [check]

    name: Benchmark / Query Performance
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-repo

      - name: Query Performance
        run: bun run --filter './benchmarks/query-performance' start

  benchmark-type-complexity:
    needs: [check]

    name: Benchmark / Type Complexity
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-repo

      - name: Type Complexity
        run: bun run --filter './benchmarks/type-complexity' start

  # PR CHECKS

  required-collector-job:
    needs:
      [
        check,
        test,
        examples,
        benchmark-memory-footprint,
        benchmark-processing-capacity,
        benchmark-query-performance,
        benchmark-type-complexity,
      ]
    if: github.event_name == 'pull_request' && always()

    name: Required Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check for failures
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1

  # END PR CHECKS
